version: "3.2"
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    image: docker_php_mysql
    networks:
      - frontend
      - backend
    environment:
      - MYSQL_HOST=docker-mysql-app
      - MYSQL_USER=smileeypin
      - MYSQL_PASSWORD=dockersql
      - MYSQL_DBS=docker_db
    volumes:
        - ./src/:/var/www/html/
    ports:
        - "30001:80"
    container_name: docker-php-app
  mysql:
    image: mysql:5.7
    networks:
      - backend
    environment:
        - MYSQL_ROOT_PASSWORD=rootpassword
        - MYSQL_USER=smileeypin
        - MYSQL_PASSWORD=dockersql
        - MYSQL_DATABASE=docker_db
    container_name: docker-mysql-app
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    depends_on:
      - mysql
    networks:
      - backend
    ports:
      - "30002:80"
    environment:
      - PMA_HOST=docker-mysql-app
      - PMA_PORT=3306
    volumes:
      - /sessions
    container_name: docker-phpmyadmin-app
networks:
  frontend:
  backend: